### ISSUE TITLE
Research Web Service to determine if we have email functionality available

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#1]
Check out service.baltimorecountymd.gov web service to determine if we already have email functionality or if that is something we need to build.

**Comment by tmccoy529** [comment]
@martypowell @sgrg1 After looking into BCPL I was able to mostly mimic what was done in that project with some minor changes. I attempted to make a place holder utility that is very basic for now that simply takes email to, from , subject, content and the email type to send. Type can be expanded but currently its checking for error email which then pulls To and From, from the web config. Like I said its very simple and hasn't been fleshed out but its a good starting point.
