### ISSUE TITLE
Determine if a User Should be Charged a Fee

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#10]
We need a function to determine if a user should be charged interest and a penalty. Original communication.

"My understanding is that since this is all paper-based now, yes, the business operator will know the due date based on the type of filing period they chose – quarterly or monthly. So if I’m paying for the month of January, I have until the end of February to send in my payment penalty-free. If I’m paying for a quarter, I have until the end of the month after quarter-end to send in my payment."

Here is an attempt at some scenarios to summaries the original communication.

**Scenario 1**
- User has chosen to submit a monthly report. 
- The current date is **within** 1 month of the month selected
- No interest or penalty should be applied

**Scenario 2**
- User has chosen to submit a monthly report. 
- The current date is **past** 1 month of the month selected
- Interest or penalty should be applied based on how far past the due date

**Scenario 3**
- User has chosen to submit a quarterly report. 
- The current date is **within** 1 month of the final month of the quarter selected
- No interest or penalty should be applied

**Scenario 4**
- User has chosen to submit a monthly report. 
- The current date is **past** 1 month of the final month of the quarter selected
- Interest or penalty should be applied based on how far past the due date

**Comment by tmccoy529** [comment]
@martypowell do we know how close to the next month if they are already past to calculate the next months penalty?

My payment is due January 1st. I have until February 1st to pay it. I pay it February 2nd so I owe a 1 month penalty. I pay it February 28th....I still only pay a 1 month penalty? I think that is accurate but wanted to make sure there isn't a caveat to this rule.

**Comment by martypowell** [comment]
> @martypowell do we know how close to the next month if they are already past to calculate the next months penalty?
> 
> My payment is due January 1st. I have until February 1st to pay it. I pay it February 2nd so I owe a 1 month penalty. I pay it February 28th....I still only pay a 1 month penalty? I think that is accurate but wanted to make sure there isn't a caveat to this rule.

That is my understanding, and we actually have tests to support this, so if this changes, well need to update that as well.

**Comment by tmccoy529** [comment]
@martypowell this is actually being handled in #49 which is currently in code review.
Re-assigning and moving to code review.
