### ISSUE TITLE
Populate error page content

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#102]
There is an error page that we redirect to if the app encounters any errors, but we need to populate this.

**Comment by martypowell** [comment]
@sdurphy can I dump this on you please?

**Comment by sdurphy** [comment]
@martypowell will this be an alternate view of the confirmation page? (Ex: Tax Sale) And if so, do we have the ability to spit out a description of what the error is on that page?

**Comment by martypowell** [comment]
@sdurphy I think for this case, we can assume something went wrong, types of errors

- Network Error - Service is not available
- Anything else - maybe we want to asay check again in a couple of minutes, you can still file in person or something like that?
