### ISSUE TITLE
We still need to get the final destination for the production page and add it to the web service.

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#115]

**Comment by martypowell** [comment]
@sdurphy can we get the production location of this page for the app?

**Comment by sdurphy** [comment]
@martypowell, the new page should be placed in the following section: https://www.baltimorecountymd.gov/Agencies/budfin/taxpayerservices/

**Comment by martypowell** [comment]
> @martypowell, the new page should be placed in the following section: https://www.baltimorecountymd.gov/Agencies/budfin/taxpayerservices/

What will the name of the page be?

**Comment by sdurphy** [comment]
We can name it "transientoccupancytax.html"

**Comment by martypowell** [comment]
thanks @sdurphy this has been completed.
