### ISSUE TITLE
Handle invalid confirmation number

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#116]
We need a way to say hey this confirmation number did match up with results. This will require some content from web services.

To recreate lookup confirmation number 700.

**Comment by tmccoy529** [comment]
@martypowell @sdurphy hey Sam, is there any specific wording or mark up you'd like to see for passing in an invalid confirmation number? I've currently just got a <p>Generic Text</p> holding some very generic text as a placeholder.
