### ISSUE TITLE
Add missing confirmation page content

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#124]
"Add some kind of verbiage to the confirmation page and email that indicates to the person submitting the payment that the interest calculated is based on payment being received in the current month. Yes, this gets tricky if the person is submitting the form on the last day of the month and have yet to remit payment, but OBF will allow a small grace period for that check to arrive/be brought in. if it’s aggregiously late, they’ll send a letter to collect additional interest and capture that outside of the system."

Note, there is an email out to webservices to provide this content.

**Comment by martypowell** [comment]
@sdurphy I added you to this, this can be satified through an email or including the content here. Or even both!

**Comment by sdurphy** [comment]
"Interest calculation is based on the current date. If your payment is not postmarked in the current month you will be assessed additional interest."

FYI - @martypowell

**Comment by martypowell** [comment]
This was completed in a previous pull request, and is located on each payment form.
