### ISSUE TITLE
Half the form clears when going backwards

### ISSUE THREAD

**Issue by tmccoy529** [baltimorecounty/react-transient-tax#165]
**Steps to replicate:**

- Fill out form for quarterly or monthly
- Add an exemption
- Fill out all identification info
- Go to review
- Then click previous all the way back to the payment interval section
- Don't make any changes
- Click next and notice that monthly tax values are still present including exemption values
- Click next and notice that Exemption Certificates are now gone
-  Fill in and click next
- Notice all fields in identification section are gone.

For a consistent experience unless the payment interval changes I would assume the form would not clear itself of any data by going backwards or forward.

**Comment by martypowell** [comment]
per @tmccoy529 's chat on friday, i can take a look at this.
