### ISSUE TITLE
console error for quarterly return type

### ISSUE THREAD

**Issue by sgrg1** [baltimorecounty/react-transient-tax#177]
[DOM] Found 3 elements with non-unique id #governmentExemptRentalCollected: (More info: https://goo.gl/9p2vKq) <input type=​"number" step=​"0.01" id=​"governmentExemptRentalCollected" name=​"governmentExemptRentalCollected" value>​ <input type=​"number" step=​"0.01" id=​"governmentExemptRentalCollected" name=​"governmentExemptRentalCollected" value>​ <input type=​"number" step=​"0.01" id=​"governmentExemptRentalCollected" name=​"governmentExemptRentalCollected" value>​

**Comment by martypowell** [comment]
@sgrg1 is this still a problem?

**Comment by sgrg1** [comment]
this has been fixed
