### ISSUE TITLE
Can't move to next page from Payment Interval Selection when switching filling types

### ISSUE THREAD

**Issue by sgrg1** [baltimorecounty/react-transient-tax#203]
First select one filing type(Monthly), select the date from date control then click "Next" to go to next page. Now click on the "Previous page" to go back to Payment Interval Selection . Now change the filing type by selecting "Quarterly" then click on the "Next" button . It shows error saying"A date must be selected before you can proceed".

**Comment by martypowell** [comment]
@sgrg1 I think this may have been addressed in #204 . please let me know if that resolves it.

**Comment by tmccoy529** [comment]
@martypowell @sgrg1 I can confirm that the branch addressing #204 does resolve this issue.
