### ISSUE TITLE
Confirmation Page Content

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#23]
We need the content to be displayed once a user has successfully completed a tax form.

At a minimum this will include the confirmation number which will be available from withing the app.

This may be very similar to #24.

**Comment by martypowell** [comment]
![image](https://user-images.githubusercontent.com/1933400/68674652-44d51c00-0524-11ea-98c4-5f8d6bbdf59c.png)

Note that some of this language will change depending on the "Payment Plan" or interval in which the user pays (monthly or quarterly)


Text Version:

{submissionDate}

{formSubmitterName},

You have successfully completed the Baltimore County Transient Occupancy Tax Return. Your confirmation number for this return is {confirmationNumber}. 

Please present this number to the appropriate Budget and Finance Official when making inquiries in regards to your Transient Occupancy Tax Return.


{confirmationNumber} Transient Occupancy Tax Return Details:



Your Payment Plan | Monthly
Month of Return | August 2019
Due Date | September 30, 2019


Occupancy Tax   Collected | $30.00
Exemptions | $0.00
Penalties | $6.15


Monthly Tax Remitted | $36.15


fyi @sdurphy

**Comment by martypowell** [comment]
@tmccoy529 @sgrg1 I tend to think the styles will change on this, so once we get here, let's talk with @sdurphy

**Comment by martypowell** [comment]
> ![image](https://user-images.githubusercontent.com/1933400/68674652-44d51c00-0524-11ea-98c4-5f8d6bbdf59c.png)
> 
> Note that some of this language will change depending on the "Payment Plan" or interval in which the user pays (monthly or quarterly)
> 
> **Text Version**:
> 
> {submissionDate}
> 
> {formSubmitterName},
> 
> You have successfully completed the Baltimore County Transient Occupancy Tax Return. Your confirmation number for this return is {confirmationNumber}.
> 
> Please present this number to the appropriate Budget and Finance Official when making inquiries in regards to your Transient Occupancy Tax Return.
> 
> {confirmationNumber} Transient Occupancy Tax Return Details:
> 
> Your Payment Plan | Monthly
> Month of Return | August 2019
> Due Date | September 30, 2019
> 
> Occupancy Tax Collected | $30.00
> Exemptions | $0.00
> Penalties | $6.15
> 
> Monthly Tax Remitted | $36.15
> 
> fyi @sdurphy

UPDATE: We would also want to include You have signed up for monthly payments; the due date for your next payment is October, 30, 2019

**Comment by sdurphy** [comment]
Adding this URL as an FYI @martypowell @tmccoy529 

http://staging.baltimorecountymd.gov/TransientTax/confirmation.html

**Comment by tmccoy529** [comment]
@sdurphy thanks, that's what I was looking for.

**Comment by martypowell** [comment]
@tmccoy529 i moved this into progress for you.
