### ISSUE TITLE
Why do I need this content needs to be populated.

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-transient-tax#99]
We need to provide content for the following "Why do I need this?" buttons (email included)

![image](https://user-images.githubusercontent.com/1933400/69544672-3512fa00-0f5e-11ea-9758-b2b5a40ab915.png)

**Comment by martypowell** [comment]
@sdurphy can i pawn this off to you?

**Comment by sdurphy** [comment]
@martypowell sure you can.

**Comment by sdurphy** [comment]
@martypowell please us the following copy approved by OBF:

Return Submitted By:
We collect this information in order to keep record of who will be submitting the payment. 

Title:
We collect this information to determine how the submitter is affiliated with the business.

**Comment by martypowell** [comment]
@sdurphy we have one for `Email`. This is what we have...

"We will send you a confirmation number that you will bring when you pay the form in person."

Is this okay?

**Comment by sdurphy** [comment]
@martypowell can you change to the following for now? (I haven't run this by Heather L yet):

"We will send a confirmation number to the email address you provide. Please bring this confirmation number with you when you submit your payment in person. "
